class AddAdditionalColumnsToCourse < ActiveRecord::Migration[7.0]
  def change
    add_column :courses, :hole_one, :integer
    add_column :courses, :hole_two, :integer
    add_column :courses, :hole_three, :integer
    add_column :courses, :hole_four, :integer
    add_column :courses, :hole_five, :integer
    add_column :courses, :hole_six, :integer
    add_column :courses, :hole_seven, :integer
    add_column :courses, :hole_eight, :integer
    add_column :courses, :hole_nine, :integer
    add_column :courses, :hole_ten, :integer
    add_column :courses, :hole_eleven, :integer
    add_column :courses, :hole_twelve, :integer
    add_column :courses, :hole_thirteen, :integer
    add_column :courses, :hole_fourteen, :integer
    add_column :courses, :hole_seventeen, :integer
    add_column :courses, :hole_eighteen, :integer
    add_column :courses, :player_one, :string
    add_column :courses, :player_two, :string
    add_column :courses, :player_three, :string
    add_column :courses, :p_one_s_one, :integer
    add_column :courses, :p_one_s_two, :integer
    add_column :courses, :p_one_s_three, :integer
    add_column :courses, :p_one_s_four, :integer
    add_column :courses, :p_one_s_five, :integer
    add_column :courses, :p_one_s_six, :integer
    add_column :courses, :p_one_s_seven, :integer
    add_column :courses, :p_one_s_eight, :integer
    add_column :courses, :p_one_s_nine, :integer
    add_column :courses, :p_one_s_ten, :integer
    add_column :courses, :p_one_s_eleven, :integer
    add_column :courses, :p_one_s_twelve, :integer
    add_column :courses, :p_one_s_thirteen, :integer
    add_column :courses, :p_one_s_fourteen, :integer
    add_column :courses, :p_one_s_fifteen, :integer
    add_column :courses, :p_one_s_sixteen, :integer
    add_column :courses, :p_one_s_seventeen, :integer
    add_column :courses, :p_one_s_eighteen, :integer
    add_column :courses, :p_two_s_one, :integer
    add_column :courses, :p_two_s_two, :integer
    add_column :courses, :p_two_s_three, :integer
    add_column :courses, :p_two_s_four, :integer
    add_column :courses, :p_two_s_five, :integer
    add_column :courses, :p_two_s_six, :integer
    add_column :courses, :p_two_s_seven, :integer
    add_column :courses, :p_two_s_eight, :integer
    add_column :courses, :p_two_s_nine, :integer
    add_column :courses, :p_two_s_ten, :integer
    add_column :courses, :p_two_s_eleven, :integer
    add_column :courses, :p_two_s_twelve, :integer
    add_column :courses, :p_two_s_thirteen, :integer
    add_column :courses, :p_two_s_fourteen, :integer
    add_column :courses, :p_two_s_fifteen, :integer
    add_column :courses, :p_two_s_sixteen, :integer
    add_column :courses, :p_two_s_seventeen, :integer
    add_column :courses, :p_two_s_eighteen, :integer
    add_column :courses, :p_three_s_one, :integer
    add_column :courses, :p_three_s_two, :integer
    add_column :courses, :p_three_s_three, :integer
    add_column :courses, :p_three_s_four, :integer
    add_column :courses, :p_three_s_five, :integer
    add_column :courses, :p_three_s_six, :integer
    add_column :courses, :p_three_s_seven, :integer
    add_column :courses, :p_three_s_eight, :integer
    add_column :courses, :p_three_s_nine, :integer
    add_column :courses, :p_three_s_ten, :integer
    add_column :courses, :p_three_s_eleven, :integer
    add_column :courses, :p_three_s_twelve, :integer
    add_column :courses, :p_three_s_thirteen, :integer
    add_column :courses, :p_three_s_fourteen, :integer
    add_column :courses, :p_three_s_fifteen, :integer
    add_column :courses, :p_three_s_sixteen, :integer
    add_column :courses, :p_three_s_seventeen, :integer
    add_column :courses, :p_three_s_eighteen, :integer
  end
end
